services:
  - type: web
    name: coffee-shop
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: supabase_db_externa # Nome que você dará ao serviço de BD externo no Render
          property: connectionString
      # Removido DATA_DIRECTORY pois não usaremos mais o disco local
    # Removida a seção 'disk' pois estamos usando Supabase
