name: Keep Render Service Alive

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          curl -sS "RENDER_SERVICE_URL" > /dev/null || echo "Ping failed"
          echo "Ping attempt completed at $(date)"
